### ISSUE TITLE
Stworzenie drzewa stanów

### ISSUE THREAD

**Issue by lukaszarczynski** [lukaszarczynski/ms_pacman_vs_ghosts#13]
Trzeba zrobić drzewo, którego korzeniem będzie jakaś początkowa pozycja, dziećmi wierzchołka będą jego sąsiedzi, którzy nie są ścianą. W wierzchołku powinna być też ocena pola obliczona podaną funkcją oceny, i ocena całej ścieżki od korzenia (np. średnia ocen wierzchołków). Dzieci wierzchołka byłyby obliczane leniwie, na żądanie algorytmu przeszukującego

**Comment by mkaim** [comment]
Możesz wyjaśnić jak ma być to używane przez algorytm przeszukujący?

**Comment by lukaszarczynski** [comment]
Np. przez A*, g(x) to odległość od roota * stała, a h(x) (lub -1*h(x)) to ocena ścieżki do wierzchołka x, dalej jak zwykły A*, tylko nie do końca, a do limitu czasu, i wybieramy najlepszy znaleziony ruch
Zamiast A* pewnie można też użyć DeepSearch, albo MCTS-a z heurystyką.
A ocena całej ścieżki chyba też będzie zależała od stanu, czyli powiedzmy, że jest dana
