### ISSUE TITLE
Klasa do wysyłania, odbierania, przechowywania wiadomości

### ISSUE THREAD

**Issue by lukaszarczynski** [lukaszarczynski/ms_pacman_vs_ghosts#7]
Łatwe wysyłanie, odbieranie, przechowywanie wiadomości, wybieranie wiadomości po typie, wybieranie wiadomości nie starszych niż (i połączenie obu warunków).

Część jest już w klasie BoardData

**Comment by michauciak** [comment]
Nareszcie wrzuciłem i scaliłem kod, może nawet działa, więc zamykam iszju.
